### PR TITLE
feat(CreateNumberMask): added option allowEmpty

### PR DESCRIPTION
**Pull request by dstroynov**
re #29

### CODE REVIEW

**Comment by renato-bohler** [comment]
Cool! I'm gonna have a deeper look into it later today.

**Comment by renato-bohler** [comment]
Some things I'd like to refine before merging:

1. I'm not sure if the input should be showing `prefix suffix` when the value isn't defined. Maybe we should add another option to display when the value isn't defined and `allowEmpty` is set to `true`. The option name could be `showWhenEmpty` and default to empty string, maybe?

2. There's an strange behavior when inputting invalid characters or zeroes on an input which allows empty. The value toggles between `0` and `undefined` for every invalid input.

issue

@dstroynov what do you think?

Other than that, everything is perfect. If you need any help please let me know. I'll probably have some more time to work on that later this week if you can't.

Thanks!

**Comment by dstroynov** [comment]
@renato-bohler Thanks for fast review, definitely it makes sense to fix it, don't know how did it miss it.
I'll take care of it in a couple of evenings, hopefully today

**Comment by renato-bohler** [comment]
I think that's ok, I can track this issue later.

Empty string makes much more sense to me. And if there's anyone else interesed in showing something else other than an empty string, then they can open an issue for that too.

**Comment by renato-bohler** [comment]
@dstroynov have you forgotten to push your last changes?

**Comment by dstroynov** [comment]
@renato-bohler I believe I didn't.
All I did was squashing the commits and pushing it force (because I don't want pollute the history with bogus commits).
Check it out, all the last changes are there.

**Comment by renato-bohler** [comment]
Oops, I was expecting another commit.

Thank you for your contribution @dstroynov !

**Pull request merged**
